### ISSUE TITLE
Pretty print transaction's gas amount in token units

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-core#3151]
##### SUMMARY
Currently, when pretty printing transactions, we display the transaction's fee in base units (but don't tell the user about the unit they are in).

For example:
```
Hash: 237be76bb6ff593d459e3c282114c49b666fe8a7b27d05affc63ffd607050346
Signer: +yyK5gqJb7x8xPASJZznZk8X8h0ilXuv39ctFYeHlCg=
        (signature: kAR1rwlWgm6eRc0Jjtfnnzq3kKoVJ8C0v9Qvqhs1FilUhxxWXr7rhWUx9pMhx/Wb270ykKnVEx9sXgt7ly5LBw==)
Content:
  Nonce:  7
  Fee:    2000 (gas limit: 1000, gas price: 2)
  Method: staking.Transfer
  Body:
    To:     oasis1qr3jc2yfhszpyy0daha2l9xjlkrxnzas0uaje4t3
    Amount: AMBER 170.0
```

Change this to also pretty print transaction's gas amount in token units.

For example, something like:
```
Hash: 237be76bb6ff593d459e3c282114c49b666fe8a7b27d05affc63ffd607050346
Signer: +yyK5gqJb7x8xPASJZznZk8X8h0ilXuv39ctFYeHlCg=
        (signature: kAR1rwlWgm6eRc0Jjtfnnzq3kKoVJ8C0v9Qvqhs1FilUhxxWXr7rhWUx9pMhx/Wb270ykKnVEx9sXgt7ly5LBw==)
Content:
  Nonce:  7
  Fee:
    Amount: AMBER 0.000002
    Gas limit: 1000
  Method: staking.Transfer
  Body:
    To:     oasis1qr3jc2yfhszpyy0daha2l9xjlkrxnzas0uaje4t3
    Amount: AMBER 170.0
```

##### ISSUE TYPE
- Feature Idea
