### ISSUE TITLE
State sync is very fragile

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-core#4329]
##### SUMMARY

Presently, [using the state sync](https://docs.oasis.dev/general/run-a-node/advanced/sync-node-using-state-sync) to quickly bootstrap a full Oasis node using [Tendermint's Light Client protocol](https://docs.tendermint.com/master/spec/light-client/) is very fragile and prone to errors.

##### ISSUE TYPE

- Bug Report

##### OASIS NODE VERSION

```
Software version: 21.3.3
Consensus:
  Consensus protocol version: 4.0.0
Runtime:
  Host protocol version:      4.0.0
  Committee protocol version: 3.0.0
Go toolchain version: 1.16.9
```
Tendermint version is:
https://github.com/oasisprotocol/oasis-core/blob/f599be7597caa6ef0e02817801f787f5ff4b0dcc/go/go.mod#L15

##### STEPS TO REPRODUCE

Configure an Oasis node to use the state sync as described in the [Sync Node Using State Sync](https://docs.oasis.dev/general/run-a-node/advanced/sync-node-using-state-sync) doc.

##### ACTUAL RESULTS

Very frequently, an Oasis Node waits forever with logs periodically saying:
```
... Discovering snapshots for 15s ...
```

From my observations, it could be because:
1. The first consensus RPC node in the list:
    ```yaml
    consensus:
    ​  tendermint:
    ​    state_sync:
          enabled: true
          trust_height: {{ trusted_height }}
          trust_hash: "{{ trusted_height_hash }}"
          consensus_node:
            - "{{ node1_grpc_endpoint }}"
            - "{{ node2_grpc_endpoint }}"        
            .. trimmed ...
            - "{{ noden_grpc_endpoint }}"
    ```
    is (currently) unavailable and light client sync doesn't know how to skip unavailable RPC nodes.

2. Connection tries to consensus RPC nodes time out too soon.
    There are appears to be no retry if a connection attempt to an RPC node fails?

As mentioned in https://github.com/oasisprotocol/oasis-core/issues/4326, if a node was initially synced with state sync and state sync is left enabled in node's configuration, a node may silently hang forever after node's restart.

##### EXPECTED RESULTS

An Oasis node would be quickly and automatically synced to the latest block height given an up-to-date trusted height and trusted height's hash.
