### ISSUE TITLE
Error: forbidden by policy

### ISSUE THREAD

**Issue by eavesmy** [oasisprotocol/oasis-core#4592]
Response `forbidden by policy` when i call contract method to emerald-web3-gateway( self node ).
I saw the response `forbidden by policy` is oasis-node response.

How can i deal this issue?

### Version
oasis-node: 
```
Software version: 21.3.9
Consensus:
  Consensus protocol version: 4.0.0
Runtime:
  Host protocol version:      4.0.0
  Committee protocol version: 3.0.0
Go toolchain version: 1.16.13
```

emerald-web3-gateway:
```
Software version: 1.3.1
Oasis SDK version: v0.1.1-0.20220223135638-61574136102a
Go toolchain version: go1.17.7
```

**Comment by kostko** [comment]
Hello based on the error expensive queries may be disabled. You can enable them on the node by setting the following in your node's configuration (replacing the used runtime ID with the correct one):
```yaml
runtime:
  # ... other configuration omitted ...

  config:
    "000000000000000000000000000000000000000000000000e2eaa99fc008f87f":
      allow_expensive_queries: true
```
